---
name: home-assistant-streamdeck-yaml
version: dev
slug: home-assistant-streamdeck-yaml
description: home-assistant-streamdeck-yaml add-on by Bas Nijholt
url: https://github.com/basnijholt/home-assistant-streamdeck-yaml-addon
hassio_api: true
hassio_role: default
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: home-assistant-streamdeck-yaml WebSocket port
  443/tcp: home-assistant-streamdeck-yaml WebSocket SSL port
devices:
  - /dev/bus/usb
panel_icon: mdi:radiator
options:
  hass_host: 192.168.1.24
  hass_token: '...'
  streamdeck_config: /config/streamdeck.yaml
  websocket_protocol: wss
schema:
  hass_host: str
  hass_token: str
  streamdeck_config: str
  websocket_protocol: str
